name: Spring_CI-CD

on:

  workflow_dispatch:

  pull_request:
    branches:
     - main
  push:
    branches:
     - feature
     
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
  
    steps :
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        
        - name: Build
          run: mvn -B clean verify
         
        - name: Upload JAR Artifact
          uses: actions/upload-artifact@v4
          with:
            name: jar-file
            path: target/*.jar

        - name: upload test result
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Junit test-reult
            path: target/surefire-reports

        - name:  Upload JaCoCo Report
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: coverage-report
            path: target/site/jacoco

  docker-publish:
    name: Build and Push Docker file
    needs: build
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GAR_REPOSITORY: ${{ secrets.GAR_REPOSITORY }}
      IMAGE_NAME: petclinic
      IMAGE_TAG: ${{ github.sha }}
    
    steps:
         
        - uses: actions/checkout@v4

        - name: Download JAR Artifact
          uses: actions/download-artifact@v4
          with:
            name: jar-file
            path: target

        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v3
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}
            project_id: ${{ secrets.GCP_PROJECT_ID }}

        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v3
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}

        - name: Configure Docker for Artifact Registry
          run: |
            gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet
          
            
        - name: Build Docker Image
          run: |
            docker build \
            -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

        - name: Run Trivy Vulnerability Scanner
          uses: aquasecurity/trivy-action@v0.36.0
          with:
            scan-type: image
            image-ref: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            format: table
            exit-code: 0
            severity: CRITICAL,HIGH
            ignore-unfixed: true
            vuln-type: os,library
            

        - name: Push Docker Image
          run: |
           docker push \
            ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  deploy:
    needs: docker-publish
    name: deploy to GKE
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GAR_REPOSITORY: ${{ secrets.GAR_REPOSITORY }}
      IMAGE_NAME: petclinic
      IMAGE_TAG: ${{ github.sha }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v3
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
    - name: Create Namespace
      run: |
        kubectl apply -f k8s/ns.yml
        sleep 10 

    - name: Deploy Kubernetes Manifests
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml

      
    - name: Verify Resources
      run: |
       kubectl get ns
       kubectl get deployments -A
    
    - name: Update Deployment Image
      run: |
        kubectl set image deployment/pet-clinic \
          pet-clinic=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          -n dev
      
    - name: Wait for Rollout
      run: |
        kubectl rollout status deployment/pet-clinic -n dev --timeout=5m
    
    - name: Verify Deployment
      run: |
        kubectl get pods -n dev
        kubectl get svc -n dev

    - name: Wait for Load Balancer IP
      run: |
        kubectl wait \
           --for=jsonpath='{.status.loadBalancer.ingress[0].ip}' \
           service/petclinic-service \
           -n dev \
           --timeout=300s

    - name: Verify Application Health
      run: |
         LB_IP=$(kubectl get svc petclinic-service -n dev \
         -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

         curl -f http://$LB_IP/
